export const API_ROUTES = {
	BASE: 'api',
	AUTH: {
		BASE: '/auth',
		login: '/login', // assuming standard auth routes, but controller uses wildcard
		WILDCARD: '/*path',
	},
	USER: {
		BASE: '/v1/user',
		ME: '/me',
		UPDATE: '/',
		LEDGER: '/:ledgerId',
	},
	LEDGER: {
		BASE: '/v1/ledger',
		CREATE: '/',
		FIND_ALL: '/',
		FIND_ONE: '/:id',
		UPDATE: '/:id',
		CREATE_CATEGORY: '/:id/category',
		UPDATE_CATEGORY: '/:id/category/:categoryId',
		DELETE_CATEGORY: '/:id/category/:categoryId',
		REMOVE_USER: '/remove/:id/:userId',
		ADD_USER: '/add/:id',
		ACCEPT_SHARE: '/share/accept',
		DELETE: '/:id',
	},
	ACCOUNT: {
		BASE: '/v1/account',
		CREATE: '/',
		TRANSFER: '/transfer',
		FIND_ALL: '/ledger/:ledgerId',
		FIND_ONE: '/:id',
		UPDATE: '/:id',
		DELETE: '/:id',
	},
	CREDIT: {
		BASE: '/v1/credit',
		CREATE: '/',
		FIND_ALL: '/ledger/:ledgerId',
		FIND_BY_ACCOUNT: '/account/:accountId',
		FIND_ONE: '/:id',
		UPDATE: '/:id',
		DELETE: '/:id',
	},
	TRANSACTION: {
		BASE: '/v1/transaction',
		CREATE: '/',
		FIND_ALL: '/ledger/:ledgerId',
		FIND_BY_CREDIT: '/credit/:creditId',
		FIND_ONE: '/:id',
		UPDATE: '/:id',
		DELETE: '/:id',
	},
	RECURRING_TRANSACTION: {
		BASE: '/v1/recurring-transaction',
		CREATE: '/',
		FIND_ALL: '/ledger/:ledgerId',
		FIND_ONE: '/:id',
		UPDATE: '/:id',
		DELETE: '/:id',
	},
	CURRENCY: {
		BASE: '/v1/currency',
		GET_EXCHANGE_RATE: '/exchange-rate',
		GET_ALL_EXCHANGE_RATES: '/exchange-rates',
		GET_ALL_REVERSED_EXCHANGE_RATES: '/exchange-rates/reversed',
	},
	JOB: {
		BASE: '/v1/job',
		CREATE_RECURRING_TRANSACTIONS: '/recurring-transactions',
		CHARGE_CREDITS_OF_MONTH: '/charge-credits-of-month',
	},
};

export const CLIENT_ROUTES = {
	HOME: '/',
	LOGIN: '/login',
	REGISTER: '/register',
	VERIFY_EMAIL: '/verify-email',
	SHARING: '/sharing',
};
